### ISSUE TITLE
Bro, open a crowndin to start translation... 

### ISSUE THREAD

**Issue by baianohak** [TinyHai/BanUninstall#11]

**Comment by TinyHai** [comment]
[Crowdin](https://crowdin.com/project/banuninstall) here you are

**Comment by baianohak** [comment]
i did the translations to brasilian Portuguese, wait for you to compile to see how is it. thank you.

**Comment by TinyHai** [comment]
> i did the translations to brasilian Portuguese, wait for you to compile to see how is it. thank you.

I got that, and I would tell you that I deleted the source file of English version because Crowdin seems not work well if I provide multiple source files in different language.

**Comment by baianohak** [comment]
i want in Brazilian Portuguese bro. is that ok?

**Comment by baianohak** [comment]
It's great. i will update some strings later. Thank you bro.

**Comment by TinyHai** [comment]
> i want in Brazilian Portuguese bro. is that ok?

It's supported in latest release. download it and check if all translations are right.

if you want to fix any translations, just correct it on Crowdin.

**Comment by TinyHai** [comment]
> > i did the translations to brasilian Portuguese, wait for you to compile to see how is it. thank you.
> 
> I got that, and I would tell you that I deleted the source file of English version because Crowdin seems not work well if I provide multiple source files in different language.

I mean that you could only translate from Chinese to what your language since then

**Comment by baianohak** [comment]
Yes,  i got it. i will update the strings on crowding later. but it's almost perfect to Brazilian Portuguese, i will try translating to English to.. can you add a black background option too?

**Comment by TinyHai** [comment]
> can you add a black background option too?

do you mean the dark mode?

**Comment by baianohak** [comment]
yes, but a pure black AMOLED background

**Comment by TinyHai** [comment]
> yes, but a pure black AMOLED background

could you give me a reason?

**Comment by baianohak** [comment]
> > yes, but a pure black AMOLED background
> 
> could you give me a reason?

hahaha, no. because i was thinking about it here and actually looks good. it's just because my interface is all pure black AMOLED. but the pop-up looks nice in material you colors too. Thanks man ;)

**Comment by TinyHai** [comment]
could you take a screenshot? let me take a look

**Comment by baianohak** [comment]
![Screenshot_20240517-112022_Bloqueio de desinstalação.png](https://github.com/TinyHai/BanUninstall/assets/99616052/5c3c2e68-6567-456e-b810-d4ababe8d3f1)

![Screenshot_20240517-112004_Bloqueio de desinstalação.png](https://github.com/TinyHai/BanUninstall/assets/99616052/790c829a-6f00-4789-ae97-31d094707e1c)


Here, it actually looks nice with the material you accent.

**Comment by TinyHai** [comment]
> ![Screenshot_20240517-112022_Bloqueio de desinstalação.png](https://private-user-images.githubusercontent.com/99616052/331628332-5c3c2e68-6567-456e-b810-d4ababe8d3f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTYxNDQsIm5iZiI6MTcxNTk1NTg0NCwicGF0aCI6Ii85OTYxNjA1Mi8zMzE2MjgzMzItNWMzYzJlNjgtNjU2Ny00NTZlLWI4MTAtZDRhYmFiZThkM2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE0MjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ODNmOWVmMWQ3NWQ5YzUwN2M1M2UwZDJmNGQ4Y2E3ZDEwMWFlNzY3ZjE3YzRkNDhmOTMzZWNhMmY3NGIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZcPKvuiMuISyAb9LwstZPK6XDyBQQHBQ6Cg98U1ypZY)
> 
> ![Screenshot_20240517-112004_Bloqueio de desinstalação.png](https://private-user-images.githubusercontent.com/99616052/331628331-790c829a-6f00-4789-ae97-31d094707e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTYxNDQsIm5iZiI6MTcxNTk1NTg0NCwicGF0aCI6Ii85OTYxNjA1Mi8zMzE2MjgzMzEtNzkwYzgyOWEtNmYwMC00Nzg5LWFlOTctMzFkMDk0NzA3ZTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE0MjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOGE1NWE4ZDY5MzZjZDczNjU3MzRiNTQ2YTNjZmJjMzMzYjc3YjkzYTczMDMzNWE5OTQ5OTg4NzZmNjViOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B-1l8l6xctdW6sG1bEUAiSkMrhW75jhGW9zA8JVqq5o)
> 
> Here, it actually looks nice with the material you accent.

If the backgroud is pure black, the corner of dialog will be ambiguous. 
Also I think the material you color is better than pure black

**Comment by baianohak** [comment]
yes,i agreed after thinking about it ;)

**Comment by baianohak** [comment]
I Updated some strings bro, check it later is you have time, maybe update in your future release :)
