### ISSUE TITLE
已经添加的APP在列表中消失后，如何恢复？

### ISSUE THREAD

**Issue by soulpursuit** [TinyHai/BanUninstall#2]
作者您好，很感谢您做了这个插件，有一段时间，我也曾有过这样的想法，害怕自己不小心点到卸载，或者放口袋误触，或者小孩子乱按卸载到重要的APP，标题中反馈的问题，请教一下应该如何反向操作

**Comment by TinyHai** [comment]
LSPosed的日志发一下

**Comment by TinyHai** [comment]
![Screenshot_2024-04-17-18-46-50-046_cn.tinyhai.ban_uninstall.jpg](https://github.com/TinyHai/BanUninstall/assets/34483077/02548629-b9b2-4046-be9f-4e2df91d8085)

底部上滑就能看到禁止卸载的应用了

**Comment by soulpursuit** [comment]
![Screenshot_2024-04-17-18-38-30-142_cn tinyhai ban_uninstall](https://github.com/TinyHai/BanUninstall/assets/48674277/967ab031-bc0d-498c-bb2a-66374f7739ae)

哦，是我用了三大金刚键的原因，挡住了😂

**Comment by TinyHai** [comment]
等有时间优化一下
