### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by hskshwjh** [TinyHai/BanUninstall#7]
Can you add a root mode to implement this module function?Thx😊

**Comment by TinyHai** [comment]
do you mean the module based on zygisk?

why do you want a root mode?

**Comment by hskshwjh** [comment]
Since not every root user will use the framework, could you please implement it?

**Comment by TinyHai** [comment]
> Since not every root user will use the framework, could you please implement it?

To clarify, what your meaning is to implement it just relying on `su`, right？

**Comment by hskshwjh** [comment]
yeh

**Comment by hskshwjh** [comment]
Device owner permissions seem to be used to implement some of your functions. It is recommended that you use root to obtain this permission and then implement it.

**Comment by TinyHai** [comment]
> Device owner permissions seem to be used to implement some of your functions. It is recommended that you use root to obtain this permission and then implement it.

It's easy to do what system app can do as root user, but if you want to block a uninstall operation, it should inject code to `system_server`, which all system services are running in.

I'm a newbie at process injection, so it's not easy for me.

I'll try to do it. Maybe it will cost many weeks or many months, I don't know.

**Comment by baianohak** [comment]
Please, start to get some translation, id love to have in on Brazilian Portuguese!!

**Comment by TinyHai** [comment]
> Please, start to get some translation, id love to have in on Brazilian Portuguese!!

PR welcome

**Comment by baianohak** [comment]
> > Please, start to get some translation, id love to have in on Brazilian Portuguese!!
> 
> PR welcome

How can I help ?

**Comment by TinyHai** [comment]
Completed #8
