### ISSUE TITLE
用不会root激活呢？

### ISSUE THREAD

**Issue by soulpursuit** [TinyHai/BanUninstall#9]
![Screenshot_2024-05-15-12-26-33-032_cn tinyhai ban_uninstall](https://github.com/TinyHai/BanUninstall/assets/48674277/2e50c7db-e50a-466b-8e26-251977f02553)

![Screenshot_2024-05-15-12-34-48-362_com miui securitycenter](https://github.com/TinyHai/BanUninstall/assets/48674277/0bea5b0d-de46-4223-98f1-d792b0fe51e9)

是不是root模式，只需要授权root权限后，我不用在lsposed中激活且勾选系统框架了？我的理解是这样。

但是一直都是未工作状态，重启手机也不行。请问是哪一步没有操作对？

**Comment by TinyHai** [comment]
操作没问题，如果没有激活说明激活失败了。
要排查就得看Log日志了
你可以重启手机，重复以上操作，然后以Root权限执行`logcat -d > /sdcard/logcat.txt`抓取日志。
或者等我下午添加个抓取日志功能再说

**Comment by TinyHai** [comment]
https://github.com/TinyHai/BanUninstall/actions/runs/9091407848 试试这个

**Comment by soulpursuit** [comment]
> https://github.com/TinyHai/BanUninstall/actions/runs/9091407848 试试这个

刚安装好的时候，进去还是显示未工作，然后我点它，直接软重启了，之后进入系统，重复操作，又软重启了，第三次进入系统，我再次点击，成功激活了，但是我手动重启手机后，依然变成未工作，再点击还是软重启，超过3次，依然不行。本来激活的状态下，我在本APP中生成日志文件，但是看到好大 60mb一个，我删除了，现在处于未工作状态，好像看不到那个提交生成日志的按钮。logcat -d > /sdcard/logcat.txt如果出现软重启也有用的话，我可以执行后发您，但是不知道github能不能提交这么大的日志文件

**Comment by TinyHai** [comment]
> > https://github.com/TinyHai/BanUninstall/actions/runs/9091407848 试试这个
> 
> 刚安装好的时候，进去还是显示未工作，然后我点它，直接软重启了，之后进入系统，重复操作，又软重启了，第三次进入系统，我再次点击，成功激活了，但是我手动重启手机后，依然变成未工作，再点击还是软重启，超过3次，依然不行。本来激活的状态下，我在本APP中生成日志文件，但是看到好大 60mb一个，我删除了，现在处于未工作状态，好像看不到那个提交生成日志的按钮。logcat -d > /sdcard/logcat.txt如果出现软重启也有用的话，我可以执行后发您，但是不知道github能不能提交这么大的日志文件

软重启应该是和 LSPosed 冲突了，你把 LSPosed 关了重启手机后应该就不会导致软重启了。
用 root 激活这个功能本就是为了不装模块准备的，如果你已经装了 LSPosed，那么就没必要使用 root 激活，直接通过 LSPosed 激活就行了。
